# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 550eb88ee10464b15626ce79c8c55e3af52a7e774f1fc770bda1d4432fb895cf5b1fcfcd172380680229e2fd3347d16f93672fa15cad650361b5c76d32fb6c49

test:
  secret_key_base: d562a68b3f44e0ed9b4e33d406d7b24aaa08d4361da45344b6c3ff01971d0de0962105270d4ea7d01b85460c09a4a1e431d1ca8edf7fda8b0eb5f82ac60da6af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
